CREATE DATABASE IF NOT EXISTS `chat`
  DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE chat;

CREATE TABLE chatitems (
	id BIGINT NOT NULL PRIMARY KEY auto_increment,
	added TIMESTAMP NOT NULL,
	user VARCHAR(64) NOT NULL,
	message VARCHAR(255) NOT NULL
);
